# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aF_GzWFLYBTVckvxLVQ0GaZ5jaLi5mZ7

## 1. Import and explore data
<p>By <a href="https://patrio.blog/">Patrik Drhlík</a></p>
<p><em>Warning: the dataset used in this project contains explicit language.</em></p>
<p><img src="https://assets.datacamp.com/production/project_561/img/southpark.png" alt></p>
<p><a href="https://en.m.wikipedia.org/wiki/South_Park">South Park</a> is a satiric American TV show. It is an adult show mainly because of its coarse language. I know every episode pretty well, but I wanted to see if I can dig up something more using text analysis.</p>
<p>We will see how the sentiments and the popularity of episodes evolve over time. We will examine the <strong>swear words</strong> and their ratio across episodes. We will also answer some questions about the show. Do you think that naughtier episodes tend to be more popular? Is Eric Cartman, the main face of the show, really the naughtiest character? We will have answers to these and more questions soon enough.</p>
<p>We will be using two datasets. One that contains every line spoken in all the 287 episodes (first 21 seasons) of the show and another that contains mean episode ratings from <a href="https://www.imdb.com/title/tt0121955">IMDB</a>. We will be joining, summarizing and visualizing until we've answered all our questions.</p>
"""

install.packages("dplyr")

# Load libraries
install.packages("readr")
install.packages("tidytext")

# Load datasets
sp_lines <- read_csv("datasets/sp_lines.csv")
sp_ratings <- read_csv("datasets/sp_ratings.csv")

# Take a look at the last six observations
tail(sp_lines)
tail(sp_ratings)

print(colnames(sp_lines))
print(colnames(sp_ratings))

"""## 2. Sentiments, swear words, and stemming
<p>Now that we have the raw data prepared, we will do some modifications. We'll utilize the combined powers of tidyverse and tidytext and make one great dataset that we will work with from now on.</p>
<p>We will join the dataset together. But most importantly, we will unnest the lines so <strong>every row of our data frame becomes a word</strong>. It will make our analysis and future visualizations very easy. We will also get rid of stop words (a, the, and, …) and assign a sentiment score based on the <a href="http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010">AFINN lexicon</a>.</p>
<p>Our new dataset will have some great new columns that will tell us a lot more about the show!</p>
"""

url <- "https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en"
en_swear_words <- read_lines(url) %>%
  tibble::tibble(word = .) %>%
  mutate(stem = SnowballC::wordStem(word))

# Load the AFINN lexicon
afinn_url <- "https://raw.githubusercontent.com/fnielsen/afinn/master/afinn/data/AFINN-111.txt"
afinn <- read_delim(afinn_url, delim = "\t", col_names = c("word", "score"))


# Join lines with episode ratings
sp <- inner_join(sp_lines, sp_ratings, by = c("season_number", "episode_number"))

# Unnest lines to words, leave out stop words and add a 
# swear_word logical column
sp_words <- sp %>%
unnest_tokens(word, line) %>%
anti_join(stop_words) %>%
left_join(afinn) %>%
mutate(word_stem = SnowballC::wordStem(word),
swear_word = word %in% en_swear_words$word | word_stem %in% en_swear_words$stem)

# View the last six observations
tail(sp_words)

"""## 3. Summarize data by episode

"""

# Group by and summarize data by episode
by_episode <- sp_words %>%
group_by(episode_id, episode_order) %>%
summarize(
swear_word_ratio = sum(swear_word) / n(),
sentiment_score = mean(value, na.rm = TRUE)) %>%
arrange(episode_order)

# Examine the last few rows of by_episode
tail(by_episode)

# What is the naughtiest episode?
(naughtiest <- by_episode[which.max(by_episode$swear_word_ratio), ])

"""## 4. South Park overall sentiment
<p><strong>It Hits the Fan</strong> – more than <strong>13%</strong> of swear words? Now that's a naughty episode! They say a swear word roughly <strong>every 8 seconds</strong> throughout the whole episode!</p>
<p>It also has a mean sentiment score of <strong>-2</strong>. That is pretty low on a scale from -5 (very negative) to +5 (very positive). <a href="https://en.wikipedia.org/wiki/Sentiment_analysis">Sentiment analysis</a> helps us decide what is the attitude of the document we aim to analyze. We are using a numeric scale, but there are other options. Some dictionaries can even classify words to say if it expresses <em>happiness</em>, <em>surprise</em>, <em>anger</em>, etc.</p>
<p>We can roughly get the idea of the episode atmosphere thanks to the sentiment score. Let's compare all the episodes together and plot the sentiment evolution.</p>
"""

# Load the ggplot2
library(ggplot2)

# Set a minimal theme for all future plots
theme_set(theme_minimal())

# Plot sentiment score for each episode
ggplot(by_episode, aes(episode_order, sentiment_score)) +
geom_point(alpha = 0.6, size = 3)

"""## 5. South Park episode popularity
<p>The trend in the previous plot showed us that the sentiment changes over time. We can also see that most of the episodes have a <strong>negative</strong> mean sentiment score.</p>
<p>Let's now take a look at IMDB ratings. They tell us everything we need to analyze episode popularity. There's nothing better than a nice plot to see if the show is becoming more or less popular over time.</p>
"""

# Plot episode ratings
ggplot(by_episode, aes(episode_order, imdb_rating)) +
geom_point(alpha = 0.6, size = 3) +
geom_vline(xintercept = naughtiest$episode_order, color = "red", linetype = "dashed")

"""## 6. Are naughty episodes more popular?
<p>South Park creators made a joke in the episode called <a href="https://en.wikipedia.org/wiki/Cancelled_(South_Park)">Cancelled</a> that a show shouldn't go past a 100 episodes. We saw that the popularity keeps dropping since then. But it's still a great show, trust me.</p>
<p>Let's take a look at something even more interesting though. I always wondered whether naughtier episodes are actually more popular. We have already prepared swear word ratio and episode rating in our <code>by_episode</code> data frame.</p>
<p><strong>Let's plot it then!</strong></p>
"""

# Plot swear word ratio over episode rating
ggplot(by_episode, aes(imdb_rating, swear_word_ratio)) +
geom_point(alpha = 0.6, size = 3) +
geom_smooth(method = "lm", se = FALSE) +
scale_y_continuous(labels = scales::percent) +
scale_x_continuous(breaks = seq(6, 10, 0.5)) +
labs(
x = "IMDB rating",
y = "Episode swear word ratio"
)

"""## 7. Comparing profanity of two characters
<p>Right now, we will create a function that will help us decide which of the two characters is naughtier. We will need a <strong>2x2 matrix</strong> to compare them. The first column has to be the <strong>number of swear words</strong> and the second the <strong>number of non-swear words</strong>. Let's take a look at the following table. Those are real numbers for <em>Cartman</em> and <em>Butters</em>.</p>
<table>
<thead>
<tr>
<th></th>
<th>swear</th>
<th>non-swear</th>
</tr>
</thead>
<tbody>
<tr>
<td>Cartman</td>
<td>1318</td>
<td>48116</td>
</tr>
<tr>
<td>Butters</td>
<td>100</td>
<td>11412</td>
</tr>
</tbody>
</table>
<p>The final step will be to apply a statistical test. Because we are comparing proportions, we can use a base R function made exactly for this purpose. Meet <a href="https://www.rdocumentation.org/packages/stats/versions/3.5.1/topics/prop.test">prop.test</a>.</p>
"""

# Create a function that compares profanity of two characters
compare_profanity <- function(char1, char2, words) {
char_1 <- filter(words, character == char1)
char_2 <- filter(words, character == char2)
char_1_summary <- summarise(char_1, swear = sum(swear_word), total = n() - sum(swear_word))
char_2_summary <- summarise(char_2, swear = sum(swear_word), total = n() - sum(swear_word))
char_both_summary <- bind_rows(char_1_summary, char_2_summary)
result <- prop.test(cbind(char_both_summary), correct = FALSE)
return(broom::tidy(result) %>% bind_cols(character = c(char1, char2)))
}

"""## 8. Is Eric Cartman the naughtiest character?
<p>Anyone who knows the show might suspect that <strong>Eric Cartman</strong> is the naughtiest character. This is what I think too. We will know for sure very soon. I picked the top speaking characters for our analysis. These will be the most relevant to compare with Cartman. They are stored in the <code>characters</code> vector.</p>
<p>We will now use <code>map_df()</code> from <code>purrr</code> to easily compare profanity of Cartman with every character in our vector. Our function <code>compare_profanity()</code> always returns a data frame thanks to the <code>tidy()</code> function from <code>broom</code>.</p>
<p>The best way to answer the question is to create a nice plot again.</p>
"""

# Vector of most speaking characters in the show
characters <- c("butters", "cartman", "kenny", "kyle", "randy", "stan", "gerald", "mr. garrison",
                "mr. mackey", "wendy", "chef", "jimbo", "jimmy", "sharon", "sheila", "stephen")

# Map compare_profanity to all characters against Cartman
prop_result <- purrr::map_df(characters, compare_profanity, "cartman", sp_words)

# Plot estimate1-estimate2 confidence intervals of all characters and color it by a p.value threshold
ggplot(prop_result, aes(x = reorder(character, estimate1-estimate2), y = estimate1-estimate2, color = p.value < 0.05)) +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), show.legend = FALSE) +
    geom_hline(yintercept = 0, col = "red", linetype = "dashed") +
    theme(axis.text.x = element_text(angle = 60, hjust = 1))

"""## 9. Let's answer some questions
<p>We included Eric Cartman in our <code>characters</code> vector so that we can easily compare him with the others. There are three main things that we should take into account when evaluating the above plot:</p>
<ol>
<li><strong>Spread of the error bar:</strong> the wider, the less words are spoken.</li>
<li><strong>Color of the error bar:</strong> blue is statistically significant result (p-value &lt; 0.05).</li>
<li><strong>Position of the error bar:</strong> prop.test estimate suggesting who is naughtier.</li>
</ol>
<p>Are we able to say if <strong>naughty episodes are more popular?</strong> And what about Eric Cartman, is he really the <strong>naughtiest character in South Park?</strong> And if not, <strong>who is it?</strong></p>
"""

# Are naughty episodes more popular? TRUE/FALSE
naughty_episodes_more_popular <- cor.test(by_episode$swear_word_ratio, by_episode$rating, method = "pearson")$p.value < 0.05

# Is Eric Cartman the naughtiest character? TRUE/FALSE
eric_cartman_naughtiest <- prop_result$character[which.min(prop_result$p.value)] == "cartman"

# If he is, assign an empty string, otherwise write his name
who_is_naughtiest <- ifelse(eric_cartman_naughtiest, "", "cartman")